version: "3.7"

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: authdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d authdb"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  app:
    build: ./cmd/server
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: pass
      DB_NAME: authdb
      JWT_SECRET: "supersecretkey"
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data:
